name: product_item_transaction
label: 产品项交易
icon: product_item_transaction
enable_search: true
fields:
  item_transaction_number:
    label: 产品项交易编号
    type: autonumber
    formula: "T-{000}"
    readonly: true
    searchable: true
    index: true
    is_name: true
  transaction_type:
    type: select
    label: 类型
    options:
      - label: 已创建
        value: Replenished
      - label: 手动调整
        value: Adjusted
      - label: 已消耗
        value: Consumed
  quantity:
    type: number
    label: 数量
  product_items:
    label: 产品项
    type: master_detail
    reference_to: product_items
list_views:
  all:
    label: 所有产品项交易
    columns:
      - field: item_transaction_number
      - field: transaction_type
      - field: quantity
        width: 100
permission_set:
  user:
    allowCreate: false
    allowDelete: false
    allowEdit: false
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true
  admin:
    allowCreate: false
    allowDelete: false
    allowEdit: false
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true
