name: product_items
label: 产品项
icon: poll
enable_files: true
enable_search: true
enable_audit: true
fields:
  product_items_number:
    label: 产品项编号
    type: autonumber
    formula: "PI-{0000}"
    readonly: true
    searchable: true
    index: true
    is_name: true
  product:
    type: lookup
    label: 产品名
    reference_to: product
    searchable: true
    required: true
  location:
    label: 位置
    type: master_detail
    reference_to: location
    required: true
    filtersFunction: !<tag:yaml.org,2002:js/function> |-
      function () {
        return "(is_inv_location eq true)";
      }
    inlineHelpText: 只有选择库存位置选项的位置，才可以与产品项关联。
  quantity:
    type: number
    label: 现存数量
    required: true
  unit:
    type: text
    label: 单位
  serial_number:
    type: text
    label: 序号
    inlineHelpText: 如果现存数量是 1，则输入序号。
list_views:
  all:
    label: 所有产品项
    columns:
      - product_items_number
      - product
      - location
      - field: quantity
        width: 100
      - unit
permission_set:
  user:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true 
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
