name: default
label: default
profiles:
  - admin
  - user
custom_actions: []
relatedList: {}
fields:
  - field: item_transaction_number
  - field: transaction_type
  - field: quantity
  - field: product_items
