name: default
label: default
profiles:
  - admin
  - user
custom_actions: []
relatedList: {}
fields:
  - field: product_items_number
  - field: product
  - field: location
  - field: quantity
  - field: unit
  - field: serial_number
